std = "love+lua51"
max_line_length = 120

exclude_files = {
    "libraries/",
    "tutorial/",
}

globals = {
    "GameObject",
    "gw", "gh", "sx", "sy",
    "default_color", "background_color", "ammo_color", "boost_color",
    "hp_color", "skill_point_color",
    "default_colors", "negative_colors", "all_colors",
    "white", "dark", "gray", "red", "green", "blue", "pink",
    "brown", "yellow", "orange", "bluegreen", "purple",
    "attacks", "attack_names",
    "id", "loop", "main_volume", "sfx_volume", "music_volume",
    "muted", "fullscreen", "display", "screen_shake", "distortion",
    "glitch", "achievements", "high_score",
    "skill_points", "bought_node_indexes", "run", "device",
    "unlocked_devices", "classes", "rank", "score",
    "found_keys", "max_tree_nodes", "spent_sp", "keys",
    "command_history",
    "enemies", "class_colors", "achievement_names",
    "achievement_descriptions", "devices",
    "current_room",
    "fn",
    "Object",
    "UUID", "KEY",
    "Timer",
    "HC",
    "setPermanentGlobals", "setTransientGlobals",
    "unlockAchievement",
    "Vector",
    "distance",
    "random",
    "round",
    "sign",
    "pushRotate",
    "pushRotateScale",
    "areRectanglesOverlapping",
    "rectangleToVertexList",
    "getPointsAlongLine",
    "createIrregularPolygon",
    "BSGRectangle",
    "chanceList",
    "pointLineDistance",
    "rotatePointAroundPoint",
    "printCenteredText",
    "drawCenteredRectangle",
    "drawRectangle",
    "addColor",
    "treeToPlayer",
    "tree",
    "types",
    "Stat",
    "Node",
    "Line",
    "Area",
    "Tim",
    "Timer",
    "Cam",
    "Camera",
    "camera",
    "fonts",
    "input",
    "save",
    "gotoRoom",
    "playMenuBack",
    "playMenuSwitch",
    "playMenuSelect",
    "playMenuError",
    "playKeystroke",
    "playMenuError",
    "playComputerLine",
    "ConsoleLine",
    "ConsoleInputLine",
    "shaders",
    "disable_expensive_shaders",
    "time",
    "timer",
    "delay",
    "first_run_ever",
    "command_history_index",
    "fadeVolume",
    "isAnySongPlaying",
    "playRandomSong",
    "Grid",
    "Director",
    "ProjectileTrails",
    "TrailParticles",
    "ExplodeParticles",
    "Tutorial",
    "Paused",
    "ScoreScreen",
    "GlitchDisplacementC",
    "draft",
    "assets",
    "flash",
    "Math",
    "Physics",
    "Key",
    "resize",
    "resizeFullscreen",
    "slow",
    "removeSave",
    "changeToDisplay",
    "target",
    "trailer_mode",
    "playGameShoot1",
    "playGameShoot2",
    "playGameEnemyDie",
    "playGameExplosion",
    "playGameFlame",
    "playGameHurt",
    "playGameItem",
    "playGameKey",
    "playGameLaser",
    "playGameLightning",
    "playMenuClick",
    "AchievementModule",
    "AboutModule",
    "Ammo",
    "AmmoEffect",
    "Attack",
    "AttackEffect",
    "BigRock",
    "Boost",
    "BoostEffect",
    "ClearModule",
    "CreditsModule",
    "CycleEffect",
    "DeviceModule",
    "DisplayModule",
    "Drone",
    "EffectsModule",
    "EnemyDeathEffect",
    "EnemyProjectile",
    "EscapeModule",
    "Explosion",
    "FullscreenModule",
    "GlitchBlockDisplacement",
    "GlitchDisplacement",
    "Glitcher",
    "GlitcherShootEffect",
    "HasteArea",
    "HelpModule",
    "HP",
    "InfoText",
    "Item",
    "LaserLine",
    "LightningLine",
    "Orbitter",
    "Player",
    "PreAttackEffect",
    "Projectile",
    "ProjectileDeathEffect",
    "Reflecteer",
    "ResolutionModule",
    "RGBShift",
    "Rock",
    "Roller",
    "RollerPool",
    "Rotator",
    "RotatorPart",
    "Sapper",
    "Seeker",
    "ShapeEffect",
    "ShapeEffect2",
    "ShockwaveDisplacement",
    "ShootEffect",
    "Shooter",
    "ShutdownModule",
    "SkillPoint",
    "SoundModule",
    "Tanker",
    "TargetParticle",
    "Trailer",
    "TrailerShootEffect",
    "TrailParticle",
    "Triad",
    "Waver",
    "WaverPreAttackEffect",
    "Shake",
    "AchievementScreenshots",
    "Achievements",
    "Classes",
    "Console",
    "SkillTree",
    "Stage",
}

ignore = {
    "212/self",
    "412/shadowing",
    "143",
    "142",
    "112",
    "631",
    "411",
    "421",
    "231",
    "311",
    "611",
    "612",
    "614",
    "621",
    "111",
    "113",
    "423",
    "433",
    "211",
    "314",
    "542",
    "431",
    "432",
    "422",
    "412",
    "121",
    "413",
}

files["main.lua"] = {
    ignore = { "011" },
}

unused_args = false
